<?php

namespace app\models;
use app\models\User;
class UserDetails extends User {
    public string $username='';
    public string $jobTitle = '';
    public string $profileImage = '';
    public string $dob = '';
    public string $phoneNumber = '';
    public string $address = '';
    public static function tableName(): string
    {
        return 'userDetails';
    }
    public function attributes(): array
    {
        return ['id', 'jobTitle', 'profileImage', 'dob', 'phoneNumber', 'address'];
    }
    public function rules():array {
        return [
            'firstname' => [self::RULE_REQUIRED],
            'lastname' => [self::RULE_REQUIRED],
            'email' => [self::RULE_REQUIRED],
            'username' => [self::RULE_REQUIRED],
            'jobtitle' => [self::RULE_REQUIRED],
            'dob' => [self::RULE_REQUIRED],
        ];
    }
    public function labels():array {
        return [
            'firstname' => 'Your first name',
            'lastname' => 'Your last name',
            'email' => 'Email',
            'username' => 'Username',
            'jobtitle' => 'Job title',
            'profileImage' => 'Profile image',
            'dob' => 'Date of birth',
            'phone' => 'Your phone number',
            'address' => 'Current address',
        ];
    }
    public function subtitle():array {
        return [
            'firstname' => 'Your first name',
            'lastname' => 'Your last name',
            'email' => 'Your email address',
            'username' => 'Your username',
            'jobtitle' => 'Job title',
            'profileImage' => 'Profile image',
            'dob' => 'Date of birth',
            'phone' => 'Your phone number',
            'address' => 'Current address',
        ];
    }

    public function save()
    {
        return parent::save(); // TODO: Change the autogenerated stub
    }
}