<?php

namespace app\models;
use app\models\User;
class UserDetails extends User {
    public int $id = 0;
    public string $username='';
    public string $firstname = '';
    public string $lastname = '';
    public string $jobTitle = '';
    public string $profileImage = '';
    public string $dob = '1900-01-01 00:00:00';
    public string $phoneNumber = '';
    public string $address = '';
    public static function tableName(): string
    {
        return 'userDetails';
    }
    public function attributes(): array
    {
        return ['id', 'username', 'firstname', 'lastname', 'jobTitle', 'profileImage', 'dob', 'phoneNumber', 'address'];
    }
    public function rules():array {
        return [
            'firstname' => [self::RULE_REQUIRED],
            'lastname' => [self::RULE_REQUIRED],
            'email' => [self::RULE_REQUIRED],
            'username' => [self::RULE_REQUIRED],
            'jobtitle' => [self::RULE_REQUIRED],
            'dob' => [self::RULE_REQUIRED],
        ];
    }
    public function labels():array {
        return [
            'firstname' => 'Your first name',
            'lastname' => 'Your last name',
            'email' => 'Email',
            'username' => 'Username',
            'jobtitle' => 'Job title',
            'profileImage' => 'Profile image',
            'dob' => 'Date of birth',
            'phone' => 'Your phone number',
            'address' => 'Current address',
        ];
    }
    public function subtitle():array {
        return [
            'firstname' => 'Your first name',
            'lastname' => 'Your last name',
            'email' => 'Your email address',
            'username' => 'Your username',
            'jobtitle' => 'Job title',
            'profileImage' => 'Profile image',
            'dob' => 'Date of birth',
            'phone' => 'Your phone number',
            'address' => 'Current address',
        ];
    }
    public function toString() {
        return "username: ".$this->username."\n".
            "jobTitle: " . $this->jobTitle . "\n" .
            "profileImage: " . $this->profileImage . "\n" .
            "dob: " . $this->dob . "\n" .
            "phoneNumber: " . $this->phoneNumber . "\n" .
            "address: " . $this->address . "\n";
    }
    public function save()
    {
        return parent::save(); // TODO: Change the autogenerated stub
    }

    public function setUsername($username)
    {
        $this->username = $username;
    }
    public function getDisplayName(): string
    {
        return $this->firstname . ' ' . $this->lastname;
    }
}